import type { ChartTextType } from '../types/chart.type';

export const ChartTextKR: ChartTextType = {
	// Misc prompts
	Line: '선',
	Candles: '캔들',
	'Hollow Candles': '빈 캔들',
	Sticks: '막대',
	Fills: '채우기',
	Color: '색상',
	'Positive color': '상승 색상',
	'Negative color': '하락 색상',
	Fill: '채우기',
	Save: '저장',
	Cancel: '취소',
	Apply: '적용',
	Reset: '초기화',
	Comparison: '비교',
	to: '~',
	'Scroll to increment': '스크롤하여 증가',
	'Click to toggle': '클릭하여 전환',
	Search: '검색',
	'Search results are limited to %1.': '검색 결과는 %1개로 제한됩니다.',

	// Settings
	Settings: '설정',
	'Y-axis scale': 'Y축 스케일',
	'Change percent': '변화율',
	Regular: '일반',
	Logarithmic: '로그',

	// Date-range selectors
	'Date Range': '날짜 범위',
	'Period selector': '기간 선택',
	D: '일',
	M: '월',
	YTD: '연초대비',
	Y: '년',
	Max: '전체',
	minute: '분',
	minutes: '분',
	hour: '시간',
	hours: '시간',
	day: '일',
	week: '주',
	month: '월',
	year: '년',
	Year: '년',
	Month: '월',
	Hour: '시간',
	Minute: '분',
	Wk: '주',

	// Drawing
	Draw: '그리기',
	'Drawing tool': '그리기 도구',
	'Snap icon to data': '데이터에 아이콘 맞춤',
	'Line color': '선 색상',
	'Line thickness': '선 두께',
	'Line style': '선 스타일',
	'Fill color': '채우기 색상',
	Text: '텍스트',
	'Text color': '텍스트 색상',
	'Label font size': '라벨 글꼴 크기',
	Bold: '굵게',
	Italic: '기울임',
	'Label font family': '라벨 글꼴',
	'Show line extension': '선 연장 표시',
	Eraser: '지우개',
	Clear: '지우기',
	'Clear all drawings': '모든 그리기 지우기',
	Callout: '콜아웃',
	Doodle: '낙서',
	Ellipse: '타원',
	Fibonacci: '피보나치',
	'Fibonacci Timezone': '피보나치 시간대',
	'Horizontal Line': '수평선',
	'Horizontal Ray': '수평 광선',
	'Arrows &amp; Icons': '화살표 및 아이콘',
	Label: '라벨',
	Polyline: '다중선',
	'Quadrant Line': '사분면선',
	Rectangle: '사각형',
	Regression: '회귀선',
	'Trend Line': '추세선',
	'Vertical Line': '수직선',

	// Indicators
	Indicators: '지표',
	Increase: '증가',
	Decrease: '감소',
	'Accumulation Distribution': '',
	'Accumulative Swing Index': '',
	'Use Volume': '거래량 사용',
	'Limit move value': '',
	Period: '기간',
	'Aroon up': '아룬 상승',
	'Aroon down': '아룬 하락',
	Increasing: '증가',
	Decreasing: '감소',
	Upper: '상단',
	Average: '평균',
	Lower: '하단',
	Field: '필드',
	Type: '유형',
	'Fast period': '빠른 기간',
	'Slow period': '느린 기간',
	Overbought: '과매수',
	Oversold: '과매도',
	'Moving Average Type': '이동평균 유형',
	'Fast MA period': '빠른 이동평균 기간',
	'Slow MA period': '느린 이동평균 기간',
	'Signal period': '신호 기간',
	MACD: 'MACD',
	Signal: '신호',
	Offset: '오프셋',
	'Points/Percent': '포인트/퍼센트',
	'Shift type': '이동 유형',
	Shift: '이동',
	Top: '상단',
	Median: '중간값',
	Bottom: '하단',
	'%K Smoothing': '%K 평활화',
	'%D Smoothing': '%D 평활화',
	Fast: '빠름',
	Slow: '느림',
	'Signal color': '신호 색상',
	'Up volume': '상승 거래량',
	'Down volume': '하락 거래량',
	Deviation: '편차',
	Depth: '깊이',
	Aroon: '아룬',
	'Awesome Oscillator': '',
	'Bollinger Bands': '볼린저 밴드',
	'Chaikin Money Flow': '',
	'Chaikin Oscillator': '',
	'Commodity Channel Index': '',
	'Disparity Index': '',
	'Moving Average': '이동평균',
	'Moving Average Deviation': '이동평균 편차',
	'Moving Average Envelope': '이동평균 엔벨로프',
	'On Balance Volume': '',
	'Relative Strength Index': 'RSI',
	'Standard Deviation': '표준편차',
	'Stochastic Oscillator': '스토캐스틱',
	Trix: 'TRIX',
	'Typical Price': '대표가격',
	Volume: '거래량',
	VWAP: 'VWAP',
	'Williams R': '윌리엄스 %R',
	'Median Price': '중간가격',
	ZigZag: '지그재그',
};
