export type ChartTextType = Partial<{
	// Misc prompts
	Line: string;
	Candles: string;
	'Hollow Candles': string;
	Sticks: string;
	Fills: string;
	Color: string;
	'Positive color': string;
	'Negative color': string;
	Fill: string;
	Save: string;
	Cancel: string;
	Apply: string;
	Reset: string;
	Comparison: string;
	to: string;
	'Scroll to increment': string;
	'Click to toggle': string;
	Search: string;
	'Search results are limited to %1.': string;

	// Settings
	Settings: string;
	'Y-axis scale': string;
	'Change percent': string;
	Regular: string;
	Logarithmic: string;

	// Date-range selectors
	'Date Range': string;
	'Period selector': string;
	D: string;
	M: string;
	YTD: string;
	Y: string;
	Max: string;
	minute: string;
	minutes: string;
	hour: string;
	hours: string;
	day: string;
	week: string;
	month: string;
	year: string;
	Year: string;
	Month: string;
	Hour: string;
	Minute: string;
	Wk: string;

	// Drawing
	Draw: string;
	'Drawing tool': string;
	'Snap icon to data': string;
	'Line color': string;
	'Line thickness': string;
	'Line style': string;
	'Fill color': string;
	Text: string;
	'Text color': string;
	'Label font size': string;
	Bold: string;
	Italic: string;
	'Label font family': string;
	'Show line extension': string;
	Eraser: string;
	Clear: string;
	'Clear all drawings': string;
	Callout: string;
	Doodle: string;
	Ellipse: string;
	Fibonacci: string;
	'Fibonacci Timezone': string;
	'Horizontal Line': string;
	'Horizontal Ray': string;
	'Arrows &amp; Icons': string;
	Label: string;
	Polyline: string;
	'Quadrant Line': string;
	Rectangle: string;
	Regression: string;
	'Trend Line': string;
	'Vertical Line': string;

	// Indicators
	Indicators: string;
	Increase: string;
	Decrease: string;
	'Accumulation Distribution': string;
	'Accumulative Swing Index': string;
	'Use Volume': string;
	'Limit move value': string;
	Period: string;
	'Aroon up': string;
	'Aroon down': string;
	Increasing: string;
	Decreasing: string;
	Upper: string;
	Average: string;
	Lower: string;
	Field: string;
	Type: string;
	'Fast period': string;
	'Slow period': string;
	Overbought: string;
	Oversold: string;
	'Moving Average Type': string;
	'Fast MA period': string;
	'Slow MA period': string;
	'Signal period': string;
	MACD: string;
	Signal: string;
	Offset: string;
	'Points/Percent': string;
	'Shift type': string;
	Shift: string;
	Top: string;
	Median: string;
	Bottom: string;
	'%K Smoothing': string;
	'%D Smoothing': string;
	Fast: string;
	Slow: string;
	'Signal color': string;
	'Up volume': string;
	'Down volume': string;
	Deviation: string;
	Depth: string;
	Aroon: string;
	'Awesome Oscillator': string;
	'Bollinger Bands': string;
	'Chaikin Money Flow': string;
	'Chaikin Oscillator': string;
	'Commodity Channel Index': string;
	'Disparity Index': string;
	'Moving Average': string;
	'Moving Average Deviation': string;
	'Moving Average Envelope': string;
	'On Balance Volume': string;
	'Relative Strength Index': string;
	'Standard Deviation': string;
	'Stochastic Oscillator': string;
	Trix: string;
	'Typical Price': string;
	Volume: string;
	VWAP: string;
	'Williams R': string;
	'Median Price': string;
	ZigZag: string;
}>;
