name: Deploy remix app

run-name: Deploy remix app to ECR by ${{github.actor}}

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      HUSKY: 0
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create env file
        run: |
          echo "VITE_OAUTH_URL=${{ secrets.VITE_OAUTH_URL }}" > .env
          echo "VITE_API_URL=${{ secrets.VITE_API_URL }}" >> .env
          echo "VITE_STOMP_URL=${{ secrets.VITE_STOMP_URL }}" >> .env
      - name: Build image
        run: |
          docker build -t ${{secrets.AWS_ORGANIZATION}}/frontend .
          docker tag ${{secrets.AWS_ORGANIZATION}}/frontend:latest ${{ secrets.AWS_ECR_FRONTEND_REPO }}:latest
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
      - name: Push image to ECR
        run: |
          docker push ${{ secrets.AWS_ECR_FRONTEND_REPO }}:latest